spring:
  application:
    name: smart-task-bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        timezone:
          default_storage: NORMALIZE_UTC

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}
